language: node_js
node_js:
  - "6"
cache:
  directories:
    - "node_modules"

before_script:
  - ./scripts/install.sh
script:
  - ./scripts/deploy.sh
  - ./scripts/tests.sh

deploy:
  provider: script
  script:
    - ./scripts/deploy.sh prd
    - ./scripts/tests.sh prd
  on:
    branch: production
