language: node_js
node_js:
  - "6"
cache:
  directories:
    - "node_modules"

before_script:
  - ./scripts/install.sh

deploy:
  - provider: script
    script: "./scripts/deploy.sh dev"
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: "./scripts/deploy.sh prd"
    skip_cleanup: true
    on:
      branch: production

branches:
  only:
  - master
  - production
