service: sample-lambda-app

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-2

package:
  exclude:
    - dist/**
    - mock/**
    - scripts/**
    - .serverless/**
    - README.md
    - node_modules/serverless/**

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
  ping:
    handler: handler.ping
    events:
      - http:
          path: /ping
          method: get
  metadata:
    handler: handler.metadata
    environment:
      GIT_ENV: ${git:branch} - ${git:sha1}
    events:
      - http:
          path: /metadata
          method: get

plugins:
  - serverless-plugin-git-variables

resources:
  Resources:
   DnsEntry:
     Type: 'AWS::Route53::RecordSet'
     Properties:
       HostedZoneId: 'ZLZOGWMKX62QG'
       Name: "${self:provider.stage}.cintia.me"
       Type: "A"
       AliasTarget:
         DNSName: { Fn::GetAtt: [ ApiGatewayDomainName, 'DistributionDomainName'] }
         HostedZoneId: 'ZLZOGWMKX62QG'
   ApiGatewayDomainName:
     Type: AWS::ApiGateway::DomainName
     Properties:
       CertificateArn: 'arn:aws:acm:us-east-1:839717296454:certificate/440c6909-474a-43ec-a42a-70cfd0e728b1'
       DomainName: "${self:provider.stage}.cintia.me"
