service: sample-lambda-app

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-2
  stage: ${opt:stage, 'dev'}

package:
  exclude:
    - scripts/**
    - .serverless/**
    - README.md
    - spec/**
    - .travis.yml
    - node_modules/**

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
  healthcheck:
    handler: handler.healthcheck
    events:
      - http:
          path: /healthcheck
          method: get
  metadata:
    handler: handler.metadata
    environment:
      GIT_ENV: ${git:sha1}
    events:
      - http:
          path: /metadata
          method: get

plugins:
  - serverless-plugin-git-variables

resources:
  Resources:
   DnsEntry:
     Type: 'AWS::Route53::RecordSet'
     Properties:
       HostedZoneId: 'ZLZOGWMKX62QG'                  # cintia.me
       Name: "${self:provider.stage}.cintia.me"
       Type: "A"
       AliasTarget:
         DNSName: { Fn::GetAtt: [ ApiGatewayDomainName, 'DistributionDomainName'] }
         HostedZoneId: 'Z2FDTNDATAQYW2'    # https://forums.aws.amazon.com/message.jspa?messageID=493441
   ApiGatewayDomainName:
      Type: AWS::ApiGateway::DomainName
      Properties:
        CertificateArn: 'arn:aws:acm:us-east-1:839717296454:certificate/440c6909-474a-43ec-a42a-70cfd0e728b1'
        DomainName: "${self:provider.stage}.cintia.me"
   ApiGatewayBase:
      Type: "AWS::ApiGateway::BasePathMapping"
      DependsOn: HelloLambdaPermissionApiGateway  #https://github.com/serverless/serverless/issues/2233
      Properties:
        BasePath: ''
        DomainName: "${self:provider.stage}.cintia.me"
        RestApiId:
          Ref: ApiGatewayRestApi
        Stage: ${self:provider.stage}
